apiVersion: v2
name: keycloak
version: 16.1.0
appVersion: 16.1.0
description: Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png

maintainers:
  - name: felipeweb
    email: fpo@felipeweb.dev
