--- 
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec: 
  acme: 
    email: {{.Values.email}}
    privateKeySecretRef: 
      name: letsencrypt-prod
    server: "https://acme-v02.api.letsencrypt.org/directory"
    solvers:
    {{ if .Values.projectID }} 
      - dns01:
          cloudDNS: 
            project: {{.Values.projectID}}
        selector:
          dnsZones:
            - funccloud.com 
            - funccloud.dev
    {{ end }}
      - http01: 
          gatewayHTTPRoute:
            parentRefs:
              - name: {{.Values.gateway.name}}
                namespace: {{.Values.gateway.namespace}}
                kind: Gateway
